### ISSUE TITLE
Sample Input Data Files

### ISSUE THREAD

**Issue by TanmayAgrawal** [the-virtual-brain/tvb-recon#57]
As in the readme it is mentioned that the input data folder must be made of:-

mri
- t1_input.nii.gz
- dwi_raw.nii
- dwi.bvec
- dwi.bval

However the sample mri files given in the repository are different.
They are- aparc+aseg.nii , brain.nii and T1.nii.
I want to run a test so as to see its working.
So please tell me how I have to specify them in the folder.
Thanks.

**Comment by liadomide** [comment]
Hi,
The current pipeline repo does not provide a complete dataset for running the pipeline, as I assume you are referring to this folder: https://github.com/the-virtual-brain/tvb-recon/tree/master/data/fsaverage_modified/mri 
This is only meant for uni-tests (see tests folder https://github.com/the-virtual-brain/tvb-recon/tree/master/tvb/recon/tests).
The documentation is correct, that is the expected input data, but we can not share a complete patient dataset, due to GDPR.
We recommend you to alter the Pegasus flow in a way that it only executes 2-3 steps (for example the part processing the T1, which we is shared in the demo data), and thus see that a flow is running. The GUI could be also developed on a small graph, and scaled later.
Does this address your concern?
Best,
Lia.
