### ISSUE TITLE
Unable to run tvb-recon docker image

### ISSUE THREAD

**Issue by TanmayAgrawal** [the-virtual-brain/tvb-recon#58]
I tried to run the docker image on my local machine using the command given in readme.

> docker run -it -v your_path_to_TVB_patients/TVB_patients/:/home/submitter/data -v your_path_to_tvb_recon/tvb-recon/:/opt/tvb-recon popaula937/tvb-recon:master-pr50 /bin/bash

However it shows the following error:-

> Unable to find image 'popaula937/tvb-recon:master-pr50' locally
> docker: Error response from daemon: pull access denied for popaula937/tvb-recon, repository does not exist or may require 'docker login': denied: requested access to the resource is denied. 

Please look into it.

**Comment by popaula937** [comment]
Hi, not sure whether you have seen that the run command has been updated in the documentation. The correct docker image to use is thevirtualbrain/tvb-recon.

**Comment by TanmayAgrawal** [comment]
Hi. I saw the updated documetation and tested it also. But I think there is an extra '/' after TVB_patients and tvb-recon in the command. It worked for me when I removed it from both the places. The run command should be:-

> docker run -it -v your_path_to_TVB_patients/TVB_patients/:/home/submitter/data -v your_path_to_tvb_recon/tvb-recon/:/opt/tvb-recon thevirtualbrain/tvb-recon /bin/bash

Should I correct it in the documentation?

**Comment by sraghuvanshi** [comment]
Hi @TanmayAgrawal,
The following command which is currently present in the documentation 
> docker run -it -v your_path_to_TVB_patients/TVB_patients/:/home/submitter/data -v your_path_to_tvb_recon/tvb-recon/:/opt/tvb-recon thevirtualbrain/tvb-recon /bin/bash

I tried to run it on my machine and it worked correctly, there was no need to remove "/" after TVB_patients and tvb_recon. 
Hence, I think the documentation is correct and requires no updates. 

You said it worked for you when you removed it from both the places, wasn't the command working with "/" at both the places? 
Because for me it is working in both cases. Also, let me know what is your OS.

## Screenshot
I'm running it on ubuntu 18.04 LTS. 
![Screenshot from 2020-02-19 23-12-53](https://user-images.githubusercontent.com/48951339/74860856-60479280-536f-11ea-917d-79f96a608cf6.png)
![Screenshot from 2020-02-19 23-33-15](https://user-images.githubusercontent.com/48951339/74861408-4b1f3380-5370-11ea-9812-84bc4c9d5e11.png)

**Comment by TanmayAgrawal** [comment]
Hello @sraghuvanshi 
I also have Ubuntu 18.04 LTS.
No its not running for me when there's a "/" at both places.
As its running in the later case for sure, then the documentation can be changed so as to assure that the command works for everyone.

**Comment by sraghuvanshi** [comment]
Hi @TanmayAgrawal 
What is the actual error that you are facing when you are using the command with "/" at both places? 
It will be great if you could share the screenshots.

**Comment by maedoc** [comment]
> No its not running for me when there's a "/" at both places.

Please copy paste the command which doesn't work.  The extra slash should not have any effect as "/home" and "/home/" are the same thing to a Linux system.

**Comment by sraghuvanshi** [comment]
Hi @TanmayAgrawal 
I think the issue you were facing is resolved. If so then it will be great if you could please close this issue. Thanks
